### ISSUE TITLE
Please add Support for the Setapp version of Marked

### ISSUE THREAD

**Issue by Tekl** [jfieber/Marked2.novaextension#1]
Its path is: `/Applications/Setapp/Marked.app`

**Comment by jfieber** [comment]
@ttscoff – Is the bundle identifier same across the different Marked 2 release channels?  Actually, adding streaming update support will require moving to the URL handler for invocation, so maybe this is a moot point.

**Comment by ttscoff** [comment]
Yes, Setapp requires apps to have a unique bundle ID for the Setapp version. com.brettterpstra.marked-setapp. The URL handler would be the cleaner solution, obviously, as it will target whatever version of Marked has claimed the url prefix.

- Brett

**Comment by jfieber** [comment]
@Tekl I have updated the main branch here adding a preference item to select the Marked 2 application path. This *should* get set correctly automatically For Most People. If you are able to download from here and install it for a test, that would be super. Otherwise I'll likely publish the update to the Nova extension directory in the next day or so.

@ttscoff I've stuck to `open -a ...`, for now, but with a fully qualified path instead of the bare app name. When using the App Store version, opening by the URL handler presents a request to grant Marked 2 access to the folder.  A sandboxing artifact I presume, and annoying as all get out, and the access grant ends when Marked 2 exits. Doing `open -a /path/to/Marked path/to/file` apparently negotiates the sandbox access behind the scenes and is a much better user experience, for now.

To set the initial preference item for the path to Marked 2, I query (mdfind) for the bundle identifier `com.brettterpstra.marked*`. I'd love to know if I'm likely to find surprises in the wild with that.  For multiple discovered installs, the ranking is: newer version wins over older version, setapp wins over non-setapp, and non-appstore wins over appstore (sandboxing convenience). Do you have any opinions about that order?

**Comment by ttscoff** [comment]
Your order of preference looks great, and you shouldn't run into any surprises with that mdquery query.

I'll have to look into why permissions don't persist, but it make sense that the URL handler triggers it. Permissions are automatically granted for any file the user manually opens, including by using open -a, but using the url handler abstracts that to asking the application to open the file automatically. Not sure I can work around the initial permission request, but I can try to make it persist better.

- Brett

**Comment by jfieber** [comment]
@Tekl version 1.0.3 is now in the Nova extension directory. Please confirm here if it works correctly for you with the Setapp version.

**Comment by Tekl** [comment]
Thanks alot. It works well. 👍
